version: "3.7"

services:
  app:
    image: nickcore/gs-accessing-data-mysql
    command: [ "--MYSQL_HOST=mysql"]
    depends_on:
      - mysql
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0
    volumes:
      - gs-accessing-data-db:/var/lib/mysql
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_DATABASE: db_example
      MYSQL_ROOT_PASSWORD: root

volumes:
  gs-accessing-data-db:
