---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-app-v2
spec:
  selector:
    matchLabels:
      app: gs-app-v2
  replicas: 3
  template:
    metadata:
      labels:
        app: gs-app-v2
    spec:
      containers:
        - name: gs-app-v2
          image: nickcore/gs-accessing-data-mysql
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: MYSQL_HOST # Setting Database host address
              value: mysql
#            - name: DB_NAME  # Setting Database name
#              value: db_example
#            - name: DB_USERNAME  # Setting Database username
#              value: springuser
#            - name: DB_PASSWORD # Setting Database password
#              value: ThePassword
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: gs-app-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: gs-app-v2
  type: NodePort

